// ═══════════════════════════════════════════════════════════════════════
// NamingEngine — 288 MBTI × Enneagram naming data
// All 16 MBTI × 18 Enneagram = 288 combinations (16 preserved + 272 generated)
// ═══════════════════════════════════════════════════════════════════════

class PersonalityName {
  final String mbti;
  final String enneagram;
  final String healthLevel;
  final String nameCanto;
  final String tagline;
  final String encourage;
  final String emoji;

  PersonalityName({
    required this.mbti,
    required this.enneagram,
    required this.healthLevel,
    required this.nameCanto,
    required this.tagline,
    this.encourage = '',
    this.emoji = '🧠',
  });
}

class NamingEngine {
  static const List<String> mbtiTypes = [
    'ENFJ', 'ENFP', 'ENTJ', 'ENTP',
    'ESFJ', 'ESFP', 'ESTJ', 'ESTP',
    'INFJ', 'INFP', 'INTJ', 'INTP',
    'ISFJ', 'ISFP', 'ISTJ', 'ISTP',
  ];

  static const List<String> enneagramTypes = [
    '1w9', '1w2',
    '2w1', '2w3',
    '3w2', '3w4',
    '4w3', '4w5',
    '5w4', '5w6',
    '6w5', '6w7',
    '7w6', '7w8',
    '8w7', '8w9',
    '9w8', '9w1',
  ];

  static final Map<String, PersonalityName> _names = {
    // ═══ Phase 1: 16 original entries (preserved) ═══
'ENFJ_5w4': PersonalityName(
  mbti: 'ENFJ', enneagram: '5w4', healthLevel: 'healthy',
  nameCanto: '高級KAM L',
  tagline: '你睇到人哋睇唔到嘅 pattern，但唔好收埋自己',
  encourage: '你嘅觀察力係天賦，唔係詛咒',
  emoji: '🧠',
),

'ENFP_7w4': PersonalityName(
  mbti: 'ENFP', enneagram: '7w4', healthLevel: 'healthy',
  nameCanto: '靈感噴泉',
  tagline: '你個腦永遠有新 idea，但都要記得落地',
  encourage: '你嘅創造力係禮物，但都要休息',
  emoji: '🌈',
),

'ENTJ_8w7': PersonalityName(
  mbti: 'ENTJ', enneagram: '8w7', healthLevel: 'healthy',
  nameCanto: '自然領袖',
  tagline: '你唔使大聲都有人跟，因為你值得',
  encourage: '你嘅 vision 係力量，但要記得聆聽',
  emoji: '👑',
),

'ENTP_7w6': PersonalityName(
  mbti: 'ENTP', enneagram: '7w6', healthLevel: 'healthy',
  nameCanto: '辯論機器',
  tagline: '你同空氣都可以拗一餐，但你其實想被明白',
  encourage: '你嘅聰明係禮物，唔好再用嚟激嬲人',
  emoji: '🔥',
),

'ESFJ_2w3': PersonalityName(
  mbti: 'ESFJ', enneagram: '2w3', healthLevel: 'healthy',
  nameCanto: '社區組長',
  tagline: '你搞掂晒所有人嘅事，但自己嗰份呢？',
  encourage: '你值得被照顧，唔好成日淨係照顧人',
  emoji: '🤝',
),

'ESFP_7w6': PersonalityName(
  mbti: 'ESFP', enneagram: '7w6', healthLevel: 'healthy',
  nameCanto: '派對心臟',
  tagline: '你有你喺度就唔會悶，但都要留時間俾自己',
  encourage: '你嘅快樂係感染性嘅，但都要俾自己喊',
  emoji: '🎉',
),

'ESTJ_1w2': PersonalityName(
  mbti: 'ESTJ', enneagram: '1w2', healthLevel: 'healthy',
  nameCanto: '人類閘機',
  tagline: '你把關嚴格到過海關都驚你，但係因為你負責任',
  encourage: '你嘅標準係高，但要記得人都會犯錯',
  emoji: '📋',
),

'ESTP_7w8': PersonalityName(
  mbti: 'ESTP', enneagram: '7w8', healthLevel: 'healthy',
  nameCanto: '行動先鋒',
  tagline: '你諗都唔諗就衝咗出去，有時係好事嚟㗎',
  encourage: '你嘅勇氣係天賦，但都要諗一諗先',
  emoji: '🎯',
),

'INFJ_4w5': PersonalityName(
  mbti: 'INFJ', enneagram: '4w5', healthLevel: 'healthy',
  nameCanto: '靈魂解讀者',
  tagline: '你未出聲佢已經知道你諗咩，但你對自己最陌生',
  encourage: '你嘅直覺係超能力，但都要信自己多啲',
  emoji: '🔮',
),

'INFP_4w5': PersonalityName(
  mbti: 'INFP', enneagram: '4w5', healthLevel: 'healthy',
  nameCanto: '深夜文青',
  tagline: '你嘅內心世界比宇宙仲大，但有時要出嚟透氣',
  encourage: '你嘅情感係深度，唔好覺得自己太敏感',
  emoji: '🌙',
),

'INTJ_5w6': PersonalityName(
  mbti: 'INTJ', enneagram: '5w6', healthLevel: 'healthy',
  nameCanto: '密室策劃師',
  tagline: '你已經諗好未來十年嘅 plan A 到 plan D',
  encourage: '你嘅策略係天賦，但有時都要信個 flow',
  emoji: '♟️',
),

'INTP_5w6': PersonalityName(
  mbti: 'INTP', enneagram: '5w6', healthLevel: 'healthy',
  nameCanto: '理論工程師',
  tagline: '你個腦永遠喺度 build system，但記得食飯',
  encourage: '你嘅分析力係禮物，但都要落地',
  emoji: '⚙️',
),

'ISFJ_9w1': PersonalityName(
  mbti: 'ISFJ', enneagram: '9w1', healthLevel: 'healthy',
  nameCanto: '人肉暖爐',
  tagline: '你靜靜雞照顧晒所有人，但你以為冇人發現',
  encourage: '你嘅溫柔係超級力量，唔好覺得理所當然',
  emoji: '🏡',
),

'ISFP_9w8': PersonalityName(
  mbti: 'ISFP', enneagram: '9w8', healthLevel: 'healthy',
  nameCanto: '低調藝術家',
  tagline: '你嘅作品代表一切，但你唔鍾意出聲',
  encourage: '你嘅美感係天賦，試下多啲俾人睇你嘅作品',
  emoji: '🎨',
),

'ISTJ_1w9': PersonalityName(
  mbti: 'ISTJ', enneagram: '1w9', healthLevel: 'healthy',
  nameCanto: '可靠支柱',
  tagline: '你永遠係最穩陣嗰個，但有時都要放鬆下',
  encourage: '你嘅可靠性係 your superpower，但都要適時放手',
  emoji: '⚖️',
),

'ISTP_5w6': PersonalityName(
  mbti: 'ISTP', enneagram: '5w6', healthLevel: 'healthy',
  nameCanto: '沉默工匠',
  tagline: '你動手做嘅嘢永遠比把口講嘅多',
  encourage: '你嘅手藝係才華，但都要試下講出嚟',
  emoji: '🔧',
),

    // ═══ Phase 2: 272 generated entries (all remaining combos) ═══
    'ENFJ_1w9': PersonalityName(
      mbti: 'ENFJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·完美溫和版',
      tagline: '你想帶領大家去最好嘅地方，而且要有 dignity',
      encourage: '你 inspire people 嘅能力係 gift，但都要 recharge',
      emoji: '🌟',
    ),
    'ENFJ_1w2': PersonalityName(
      mbti: 'ENFJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·改革支援版',
      tagline: '你 inspire 人嘅方式係以身作則',
      encourage: '你帶領人成長係 mission，但要俾人自己行',
      emoji: '🌟',
    ),
    'ENFJ_2w1': PersonalityName(
      mbti: 'ENFJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·無私守則版',
      tagline: '你付出嘅愛中有 boundary，係成熟嘅關懷',
      encourage: '你嘅關懷有 boundary 係成熟嘅愛',
      emoji: '🌟',
    ),
    'ENFJ_2w3': PersonalityName(
      mbti: 'ENFJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·熱心成就版',
      tagline: '你照顧每一個人，仲要照顧得好好睇睇',
      encourage: '你嘅付出令世界更好，但都要收吓禮物',
      emoji: '🌟',
    ),
    'ENFJ_3w2': PersonalityName(
      mbti: 'ENFJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·耀眼協作版',
      tagline: '你嘅領導魅力令人信服，但你更想人成長',
      encourage: '你嘅影響力係真嘅，但你本身就已經好夠',
      emoji: '🌟',
    ),
    'ENFJ_3w4': PersonalityName(
      mbti: 'ENFJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·真實成就版',
      tagline: '你帶動群眾嘅方式好有感染力同深度',
      encourage: '你嘅 leadership 有深度，值得被 respect',
      emoji: '🌟',
    ),
    'ENFJ_4w3': PersonalityName(
      mbti: 'ENFJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·獨特展演版',
      tagline: '你希望每個人嘅 unique 都被看見',
      encourage: '你令每個人 feel seen 係你嘅 superpower',
      emoji: '🌟',
    ),
    'ENFJ_4w5': PersonalityName(
      mbti: 'ENFJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·深度原創版',
      tagline: '你對人性嘅理解好深，係天生嘅 mentor',
      encourage: '你嘅人性 insight 係天賦，要信自己',
      emoji: '🌟',
    ),
    'ENFJ_5w6': PersonalityName(
      mbti: 'ENFJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·系統思維版',
      tagline: '你帶領團隊時有晒計劃，唔係淨係講夢想',
      encourage: '你嘅 vision 加 plan 係不可阻擋嘅',
      emoji: '🌟',
    ),
    'ENFJ_6w5': PersonalityName(
      mbti: 'ENFJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·審慎智慧版',
      tagline: '你為人著想嘅同時會考慮所有風險',
      encourage: '你對人嘅 care 同 preparedness 令人安心',
      emoji: '🌟',
    ),
    'ENFJ_6w7': PersonalityName(
      mbti: 'ENFJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·靈活應變版',
      tagline: '你令身邊人 feel safe 又充滿希望',
      encourage: '你嘅 positivity 同 care 係最好嘅禮物',
      emoji: '🌟',
    ),
    'ENFJ_7w6': PersonalityName(
      mbti: 'ENFJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·歡樂策劃版',
      tagline: '你嘅正能量感染全場，但不忘照顧細節',
      encourage: '你嘅 energy 係感染力，但都要俾自己 rest',
      emoji: '🌟',
    ),
    'ENFJ_7w8': PersonalityName(
      mbti: 'ENFJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·大膽前進版',
      tagline: '你激勵人嘅方式係大膽又充滿熱情',
      encourage: '你嘅 passion 係 contagious，continue inspiring',
      emoji: '🌟',
    ),
    'ENFJ_8w7': PersonalityName(
      mbti: 'ENFJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·強大享樂版',
      tagline: '你溫柔但 powerful，係令人信服嘅領袖',
      encourage: '你嘅溫柔同力量結合係最 powerful 嘅',
      emoji: '🌟',
    ),
    'ENFJ_8w9': PersonalityName(
      mbti: 'ENFJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·從容掌控版',
      tagline: '你嘅影響力係來自包容而不是壓逼',
      encourage: '你嘅 inclusive leadership 係榜樣',
      emoji: '🌟',
    ),
    'ENFJ_9w8': PersonalityName(
      mbti: 'ENFJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·溫和堅韌版',
      tagline: '你和諧地帶領眾人，唔需要大聲宣示',
      encourage: '你 calm 咁帶領眾人係一種藝術',
      emoji: '🌟',
    ),
    'ENFJ_9w1': PersonalityName(
      mbti: 'ENFJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🌟 人群點燈者·和諧原則版',
      tagline: '你創造嘅 community 係包容而有序嘅',
      encourage: '你創造嘅和諧 community 係你嘅 legacy',
      emoji: '🌟',
    ),
    'ENFP_1w9': PersonalityName(
      mbti: 'ENFP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·完美溫和版',
      tagline: '你嘅理想主義帶住溫柔嘅堅持',
      encourage: '你嘅理想主義係 beautiful，但要接受現實嘅 messiness',
      emoji: '🌈',
    ),
    'ENFP_1w2': PersonalityName(
      mbti: 'ENFP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·改革支援版',
      tagline: '你想用你嘅熱情去令世界更美好',
      encourage: '你嘅熱情同善意可以 change the world',
      emoji: '🌈',
    ),
    'ENFP_2w1': PersonalityName(
      mbti: 'ENFP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·無私守則版',
      tagline: '你鼓勵人嘅方式溫暖又唔失原則',
      encourage: '你鼓勵人嘅方式係 gift，但要記得自己都需要 support',
      emoji: '🌈',
    ),
    'ENFP_2w3': PersonalityName(
      mbti: 'ENFP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·熱心成就版',
      tagline: '你嘅正能量感染人，仲要感染得好好睇',
      encourage: '你嘅正能量係 contagious，keep shining',
      emoji: '🌈',
    ),
    'ENFP_3w2': PersonalityName(
      mbti: 'ENFP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·耀眼協作版',
      tagline: '你唔止有夢想，仲有能力令 dreams happen',
      encourage: '你嘅 dreams 加上你嘅魅力可以 achieve anything',
      emoji: '🌈',
    ),
    'ENFP_3w4': PersonalityName(
      mbti: 'ENFP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·真實成就版',
      tagline: '你嘅創意要有 originality，唔係 copycat',
      encourage: '你嘅 originality 係最珍貴嘅嘢',
      emoji: '🌈',
    ),
    'ENFP_4w3': PersonalityName(
      mbti: 'ENFP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·獨特展演版',
      tagline: '你嘅 imagination 係藝術級嘅，而且你 show off',
      encourage: '你嘅 imagination 係無限嘅，share it with the world',
      emoji: '🌈',
    ),
    'ENFP_4w5': PersonalityName(
      mbti: 'ENFP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·深度原創版',
      tagline: '你嘅內心世界五彩繽紛，係靈感嘅源頭',
      encourage: '你內在世界嘅 richness 係靈感嘅來源',
      emoji: '🌈',
    ),
    'ENFP_5w4': PersonalityName(
      mbti: 'ENFP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·博學創作版',
      tagline: '你對有興趣嘅 topic 可以 deep dive 到痴線',
      encourage: '你嘅 curiosity 係 treasure，keep exploring',
      emoji: '🌈',
    ),
    'ENFP_5w6': PersonalityName(
      mbti: 'ENFP', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·系統思維版',
      tagline: '你探索世界時會做足功課，唔係亂嚟',
      encourage: '你嘅探索精神加 preparation 係無敵',
      emoji: '🌈',
    ),
    'ENFP_6w5': PersonalityName(
      mbti: 'ENFP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·審慎智慧版',
      tagline: '你對新 idea 興奮但又會想太多，典型 ENFP',
      encourage: '你嘅 excitement 同 depth 係獨一無二嘅',
      emoji: '🌈',
    ),
    'ENFP_6w7': PersonalityName(
      mbti: 'ENFP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·靈活應變版',
      tagline: '你帶俾人歡樂，但自己都需要安全感',
      encourage: '你帶俾人 joy，但都要俾自己 stability',
      emoji: '🌈',
    ),
    'ENFP_7w6': PersonalityName(
      mbti: 'ENFP', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·歡樂策劃版',
      tagline: '你係 possibilities 嘅化身，冇嘢係唔可能',
      encourage: '你嘅 possibilities mindset 係 superpower',
      emoji: '🌈',
    ),
    'ENFP_7w8': PersonalityName(
      mbti: 'ENFP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·大膽前進版',
      tagline: '你嘅熱情係傳染病，人人都想跟你玩',
      encourage: '你嘅 free spirit 係 contagious，fly high',
      emoji: '🌈',
    ),
    'ENFP_8w7': PersonalityName(
      mbti: 'ENFP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·強大享樂版',
      tagline: '你 free spirit 但又有強大嘅存在感',
      encourage: '你嘅 presence 同 energy 係 magnetic',
      emoji: '🌈',
    ),
    'ENFP_8w9': PersonalityName(
      mbti: 'ENFP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·從容掌控版',
      tagline: '你隨和但唔好惹，內心有條底線',
      encourage: '你隨和但 powerful，呢個係最好嘅你',
      emoji: '🌈',
    ),
    'ENFP_9w8': PersonalityName(
      mbti: 'ENFP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·溫和堅韌版',
      tagline: '你 open-minded 但又有自己嘅堅持',
      encourage: '你嘅 open mind 係禮物，但都要有 own voice',
      emoji: '🌈',
    ),
    'ENFP_9w1': PersonalityName(
      mbti: 'ENFP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🌈 靈感拓荒者·和諧原則版',
      tagline: '你同乜人都玩得埋，但心中有價值觀',
      encourage: '你 connect 到所有人嘅能力係天賦',
      emoji: '🌈',
    ),
    'ENTJ_1w9': PersonalityName(
      mbti: 'ENTJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·完美溫和版',
      tagline: '你唔單止要贏，仲要以最完美嘅方式贏',
      encourage: '你嘅標準成就 greatness，但要包容人性嘅 imperfection',
      emoji: '👑',
    ),
    'ENTJ_1w2': PersonalityName(
      mbti: 'ENTJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·改革支援版',
      tagline: '你帶團隊唔止要成果，仲要 everyone grows',
      encourage: '你帶領團隊時 tight 得嚟都要有 compassion',
      emoji: '👑',
    ),
    'ENTJ_2w1': PersonalityName(
      mbti: 'ENTJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·無私守則版',
      tagline: '你幫人成長係有 purpose 嘅，唔係為咗討好',
      encourage: '你幫助團隊成長係美德，但要俾人犯错',
      emoji: '👑',
    ),
    'ENTJ_2w3': PersonalityName(
      mbti: 'ENTJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·熱心成就版',
      tagline: '你領導嘅方式係帶住人一齊贏，唔係自己贏',
      encourage: '你嘅 leadership 令人欽佩，但要留時間俾自己',
      emoji: '👑',
    ),
    'ENTJ_3w2': PersonalityName(
      mbti: 'ENTJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·耀眼協作版',
      tagline: '你唔淨止要成功，仲要成功得受人愛戴',
      encourage: '你嘅成就令人 respect，但 process 同結果一樣重要',
      emoji: '👑',
    ),
    'ENTJ_3w4': PersonalityName(
      mbti: 'ENTJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·真實成就版',
      tagline: '你追求卓越，但係以你獨特嘅風格',
      encourage: '你追求卓越係好事，但唔好活喺 hustle culture 入面',
      emoji: '👑',
    ),
    'ENTJ_4w3': PersonalityName(
      mbti: 'ENTJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·獨特展演版',
      tagline: '你想做領袖入面最有品味嗰個',
      encourage: '你嘅獨特領導風格係資產，唔好懷疑自己',
      emoji: '👑',
    ),
    'ENTJ_4w5': PersonalityName(
      mbti: 'ENTJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·深度原創版',
      tagline: '你嘅 vision 有深度，唔係得個殼',
      encourage: '你嘅 vision 有 depth，係好珍貴嘅',
      emoji: '👑',
    ),
    'ENTJ_5w4': PersonalityName(
      mbti: 'ENTJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·博學創作版',
      tagline: '你靠智慧領導，唔係靠把聲大',
      encourage: '你嘅智慧領導係禮物，但都要 listen to 直覺',
      emoji: '👑',
    ),
    'ENTJ_5w6': PersonalityName(
      mbti: 'ENTJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·系統思維版',
      tagline: '你做每一個決定之前都有晒 data backing',
      encourage: '你嘅策略完美，但要留空間俾 spontaneity',
      emoji: '👑',
    ),
    'ENTJ_6w5': PersonalityName(
      mbti: 'ENTJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·審慎智慧版',
      tagline: '你信自己嘅判斷，但永遠有 back up plan',
      encourage: '你嘅準備功夫充足，但要信自己可以 handle',
      emoji: '👑',
    ),
    'ENTJ_6w7': PersonalityName(
      mbti: 'ENTJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·靈活應變版',
      tagline: '你大膽進取但步步為營，好有策略',
      encourage: '你大膽又謹慎，係最好嘅組合',
      emoji: '👑',
    ),
    'ENTJ_7w6': PersonalityName(
      mbti: 'ENTJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·歡樂策劃版',
      tagline: '你唔怕改變，但每次變都有 reason',
      encourage: '你嘅 plan 好宏大，但 execution 先係關鍵',
      emoji: '👑',
    ),
    'ENTJ_7w8': PersonalityName(
      mbti: 'ENTJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·大膽前進版',
      tagline: '你嘅 vision 大到嚇親人，但你 carry 得到',
      encourage: '你嘅野心冇邊際，但要照顧好自己先',
      emoji: '👑',
    ),
    'ENTJ_8w9': PersonalityName(
      mbti: 'ENTJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·從容掌控版',
      tagline: '你有權威但唔濫用，係成熟嘅領導者',
      encourage: '你嘅權威唔需要 prove，calm confidence 就夠',
      emoji: '👑',
    ),
    'ENTJ_9w8': PersonalityName(
      mbti: 'ENTJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·溫和堅韌版',
      tagline: '你 calm 咁掌控大局，唔需要大聲',
      encourage: '你 calm leadership 係成熟嘅表現',
      emoji: '👑',
    ),
    'ENTJ_9w1': PersonalityName(
      mbti: 'ENTJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '👑 宏圖指揮官·和諧原則版',
      tagline: '你帶領團隊走向和諧共贏，唔係獨裁',
      encourage: '你帶領團隊和諧進步，呢個係最好嘅 legacy',
      emoji: '👑',
    ),
    'ENTP_1w9': PersonalityName(
      mbti: 'ENTP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·完美溫和版',
      tagline: '你辯論都要辯到完美，對家冇位入',
      encourage: '你嘅 argument 好 sharp，但有時 listening 比 debating 重要',
      emoji: '🔥',
    ),
    'ENTP_1w2': PersonalityName(
      mbti: 'ENTP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·改革支援版',
      tagline: '你 challenge 人係因為你想幫佢進步',
      encourage: '你 challenge 人係為咗成長，但都要有同理心',
      emoji: '🔥',
    ),
    'ENTP_2w1': PersonalityName(
      mbti: 'ENTP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·無私守則版',
      tagline: '你同人 debate 時其實好 care 對方感受',
      encourage: '你 debate 時可以 warm 啲，唔使永遠做 devil advocate',
      emoji: '🔥',
    ),
    'ENTP_2w3': PersonalityName(
      mbti: 'ENTP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·熱心成就版',
      tagline: '你 argue 贏之餘仲要人覺得你好有魅力',
      encourage: '你嘅 ideas 好精彩，但都要有 follow-through',
      emoji: '🔥',
    ),
    'ENTP_3w2': PersonalityName(
      mbti: 'ENTP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·耀眼協作版',
      tagline: '你唔只想贏個 argument，仲想得到認同',
      encourage: '你贏得 debates，但 relationships 唔係要贏嘅',
      emoji: '🔥',
    ),
    'ENTP_3w4': PersonalityName(
      mbti: 'ENTP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·真實成就版',
      tagline: '你嘅 ideas 要 original 先值得講出口',
      encourage: '你嘅 originality 係寶藏，但都要接受平凡嘅 moment',
      emoji: '🔥',
    ),
    'ENTP_4w3': PersonalityName(
      mbti: 'ENTP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·獨特展演版',
      tagline: '你啲 idea 又爆又靚，但你唔肯停喺一個',
      encourage: '你嘅創意無限，但要 focus 完成一個先',
      emoji: '🔥',
    ),
    'ENTP_4w5': PersonalityName(
      mbti: 'ENTP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·深度原創版',
      tagline: '你鍾意探討離經叛道嘅 concept，越 deep 越好',
      encourage: '你嘅 deep dive 好正，但都要浮上水面透氣',
      emoji: '🔥',
    ),
    'ENTP_5w4': PersonalityName(
      mbti: 'ENTP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·博學創作版',
      tagline: '你嘅 arguments 背後有深厚嘅知識支撐',
      encourage: '你嘅知識廣博，但要 share 多啲俾世界',
      emoji: '🔥',
    ),
    'ENTP_5w6': PersonalityName(
      mbti: 'ENTP', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·系統思維版',
      tagline: '你辯論前已經諗好晒對方會點反駁',
      encourage: '你嘅準備好充足，係時候跳出去試',
      emoji: '🔥',
    ),
    'ENTP_6w5': PersonalityName(
      mbti: 'ENTP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·審慎智慧版',
      tagline: '你鍾意 challenge authority，但會做足 research',
      encourage: '你嘅 critical thinking 係武器，但都要信人',
      emoji: '🔥',
    ),
    'ENTP_6w7': PersonalityName(
      mbti: 'ENTP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·靈活應變版',
      tagline: '你 rapid fire 咁出 ideas，但要小心 burn out',
      encourage: '你嘅 adaptability 係 superpower',
      emoji: '🔥',
    ),
    'ENTP_7w8': PersonalityName(
      mbti: 'ENTP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·大膽前進版',
      tagline: '你唔怕得罪人，真理比 feeling 重要',
      encourage: '你大膽探索係好事，但都要考慮 consequences',
      emoji: '🔥',
    ),
    'ENTP_8w7': PersonalityName(
      mbti: 'ENTP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·強大享樂版',
      tagline: '你 debate 時氣場強大，對手未開口已輸一半',
      encourage: '你嘅 debating 氣場好強，但都要俾 space 人哋',
      emoji: '🔥',
    ),
    'ENTP_8w9': PersonalityName(
      mbti: 'ENTP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·從容掌控版',
      tagline: '你選擇性出手，但一出手就致命',
      encourage: '你選擇性出手係智慧嘅表現',
      emoji: '🔥',
    ),
    'ENTP_9w8': PersonalityName(
      mbti: 'ENTP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·溫和堅韌版',
      tagline: '你內心好多意見，但會揀時機先講',
      encourage: '你睇到好多 possibilities，但都要 commit 一個',
      emoji: '🔥',
    ),
    'ENTP_9w1': PersonalityName(
      mbti: 'ENTP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🔥 創新辯士·和諧原則版',
      tagline: '你鍾意 intellectual harmony，但唔代表冇立場',
      encourage: '你嘅 intellectual 彈性係禮物，但要站穩立場',
      emoji: '🔥',
    ),
    'ESFJ_1w9': PersonalityName(
      mbti: 'ESFJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·完美溫和版',
      tagline: '你照顧社群嘅方式有條不紊，係成熟嘅關懷',
      encourage: '你照顧人嘅方式好有 quality，但都要照顧自己',
      emoji: '🤝',
    ),
    'ESFJ_1w2': PersonalityName(
      mbti: 'ESFJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·改革支援版',
      tagline: '你幫人嘅時候有原則，唔係盲目順從',
      encourage: '你嘅社群精神係 inspring，continue your good work',
      emoji: '🤝',
    ),
    'ESFJ_2w1': PersonalityName(
      mbti: 'ESFJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·無私守則版',
      tagline: '你嘅慷慨有 boundary，係 healthy 嘅付出',
      encourage: '你嘅 care 有 boundary 係 healthy',
      emoji: '🤝',
    ),
    'ESFJ_3w2': PersonalityName(
      mbti: 'ESFJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·耀眼協作版',
      tagline: '你 organise 活動嘅能力令人佩服',
      encourage: '你嘅 organisation 同 warmth 係 best combo',
      emoji: '🤝',
    ),
    'ESFJ_3w4': PersonalityName(
      mbti: 'ESFJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·真實成就版',
      tagline: '你 care 人嘅方式好真摯，唔係做 show',
      encourage: '你嘅真摯關懷係最有價值嘅嘢',
      emoji: '🤝',
    ),
    'ESFJ_4w3': PersonalityName(
      mbti: 'ESFJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·獨特展演版',
      tagline: '你嘅社交魅力帶一點獨特嘅氣質',
      encourage: '你嘅獨特社交魅力係你嘅 signature',
      emoji: '🤝',
    ),
    'ESFJ_4w5': PersonalityName(
      mbti: 'ESFJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·深度原創版',
      tagline: '你對人際關係嘅 insight 好深',
      encourage: '你對人際關係嘅 insight 好珍貴',
      emoji: '🤝',
    ),
    'ESFJ_5w4': PersonalityName(
      mbti: 'ESFJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·博學創作版',
      tagline: '你 understanding 人嘅方式既有 warmth 又有 depth',
      encourage: '你嘅 understanding 加 warmth 係 rare gift',
      emoji: '🤝',
    ),
    'ESFJ_5w6': PersonalityName(
      mbti: 'ESFJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·系統思維版',
      tagline: '你照顧人之前已經做好晒 research',
      encourage: '你嘅 preparedness 同 care 令人安心',
      emoji: '🤝',
    ),
    'ESFJ_6w5': PersonalityName(
      mbti: 'ESFJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·審慎智慧版',
      tagline: '你係第一個注意到 group dynamics 嘅人',
      encourage: '你嘅 group awareness 係天賦',
      emoji: '🤝',
    ),
    'ESFJ_6w7': PersonalityName(
      mbti: 'ESFJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·靈活應變版',
      tagline: '你令成個 group feel connected 同 safe',
      encourage: '你令 group feel connected 係你最叻嘅嘢',
      emoji: '🤝',
    ),
    'ESFJ_7w6': PersonalityName(
      mbti: 'ESFJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·歡樂策劃版',
      tagline: '你帶動氣氛但不忘照顧每個人嘅需要',
      encourage: '你帶動氣氛不忘照顧每個人，呢個係 mature',
      emoji: '🤝',
    ),
    'ESFJ_7w8': PersonalityName(
      mbti: 'ESFJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·大膽前進版',
      tagline: '你嘅 hospitality 係大膽又溫暖嘅',
      encourage: '你嘅 hospitality 同 energy 係 contagious',
      emoji: '🤝',
    ),
    'ESFJ_8w7': PersonalityName(
      mbti: 'ESFJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·強大享樂版',
      tagline: '你 protect 你嘅 people 時係好強勢嘅',
      encourage: '你 protect 你嘅 people 係你嘅 strength',
      emoji: '🤝',
    ),
    'ESFJ_8w9': PersonalityName(
      mbti: 'ESFJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·從容掌控版',
      tagline: '你嘅影響力來自真誠而非操控',
      encourage: '你嘅 genuine influence 係 most powerful 嘅',
      emoji: '🤝',
    ),
    'ESFJ_9w8': PersonalityName(
      mbti: 'ESFJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·溫和堅韌版',
      tagline: '你隨和地 hold 住成個場面',
      encourage: '你 chill 咁 hold 住全場，係一種藝術',
      emoji: '🤝',
    ),
    'ESFJ_9w1': PersonalityName(
      mbti: 'ESFJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🤝 社群樞紐·和諧原則版',
      tagline: '你用溫暖去建立和諧嘅社群',
      encourage: '你建立嘅和諧社群係你嘅 legacy',
      emoji: '🤝',
    ),
    'ESFP_1w9': PersonalityName(
      mbti: 'ESFP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·完美溫和版',
      tagline: '你帶歡樂俾人，仲要帶得有 quality',
      encourage: '你帶俾人嘅快樂有 quality，keep shining',
      emoji: '🎉',
    ),
    'ESFP_1w2': PersonalityName(
      mbti: 'ESFP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·改革支援版',
      tagline: '你令人開心嘅方式係溫暖而真摯嘅',
      encourage: '你嘅 warmth 同 joy 係 healing',
      emoji: '🎉',
    ),
    'ESFP_2w1': PersonalityName(
      mbti: 'ESFP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·無私守則版',
      tagline: '你對人好但唔會 lost yourself',
      encourage: '你對人好不忘自己，呢個係 healthy',
      emoji: '🎉',
    ),
    'ESFP_2w3': PersonalityName(
      mbti: 'ESFP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·熱心成就版',
      tagline: '你令人 feel special，係你嘅天賦',
      encourage: '你令 each person feel special 係你嘅 superpower',
      emoji: '🎉',
    ),
    'ESFP_3w2': PersonalityName(
      mbti: 'ESFP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·耀眼協作版',
      tagline: '你表演時嘅感染力係天生嘅 entertainer',
      encourage: '你嘅 entertainment 係天生嘅 talent',
      emoji: '🎉',
    ),
    'ESFP_3w4': PersonalityName(
      mbti: 'ESFP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·真實成就版',
      tagline: '你嘅演出有 authenticity 同 depth',
      encourage: '你嘅演出有 depth，係你嘅 signature',
      emoji: '🎉',
    ),
    'ESFP_4w3': PersonalityName(
      mbti: 'ESFP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·獨特展演版',
      tagline: '你嘅 star quality 同獨特魅力冇得輸',
      encourage: '你嘅 star quality 係 undeniable',
      emoji: '🎉',
    ),
    'ESFP_4w5': PersonalityName(
      mbti: 'ESFP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·深度原創版',
      tagline: '你快樂嘅外表下有豐富嘅內心世界',
      encourage: '你嘅內心世界同外向 charm 係 beautiful combo',
      emoji: '🎉',
    ),
    'ESFP_5w4': PersonalityName(
      mbti: 'ESFP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·博學創作版',
      tagline: '你對享受 life 嘅學問有深度研究',
      encourage: '你對生活 enjoying 嘅研究係深度',
      emoji: '🎉',
    ),
    'ESFP_5w6': PersonalityName(
      mbti: 'ESFP', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·系統思維版',
      tagline: '你玩之前會做好 research，係精明玩家',
      encourage: '你 play hard 嘅背後有 smart preparation',
      emoji: '🎉',
    ),
    'ESFP_6w5': PersonalityName(
      mbti: 'ESFP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·審慎智慧版',
      tagline: '你帶動氣氛但同時感知到 each vibe',
      encourage: '你感知 vibes 嘅能力係 gift',
      emoji: '🎉',
    ),
    'ESFP_6w7': PersonalityName(
      mbti: 'ESFP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·靈活應變版',
      tagline: '你令每一刻都係 celebration',
      encourage: '你令每一刻都係 celebration，繼續 shine',
      emoji: '🎉',
    ),
    'ESFP_7w8': PersonalityName(
      mbti: 'ESFP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·大膽前進版',
      tagline: '你玩得最盡最大，live life to the fullest',
      encourage: '你 live life to the fullest，inspire us all',
      emoji: '🎉',
    ),
    'ESFP_8w7': PersonalityName(
      mbti: 'ESFP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·強大享樂版',
      tagline: '你嘅 energy 同魅力係 magnetic',
      encourage: '你嘅 magnetic energy 係 gift',
      emoji: '🎉',
    ),
    'ESFP_8w9': PersonalityName(
      mbti: 'ESFP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·從容掌控版',
      tagline: '你 enjoy life 但有自己嘅界線',
      encourage: '你 enjoy life 有 boundaries，係 mature 嘅 fun',
      emoji: '🎉',
    ),
    'ESFP_9w8': PersonalityName(
      mbti: 'ESFP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·溫和堅韌版',
      tagline: '你 chill 同 fun 嘅 vibe 令人想親近',
      encourage: '你 chill 同 fun 嘅 vibe 係最吸引人嘅',
      emoji: '🎉',
    ),
    'ESFP_9w1': PersonalityName(
      mbti: 'ESFP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🎉 活力展演者·和諧原則版',
      tagline: '你帶俾人歡樂嘅同時蘊藏 wisdom',
      encourage: '你嘅 joy 同 wisdom 係 perfect balance',
      emoji: '🎉',
    ),
    'ESTJ_1w9': PersonalityName(
      mbti: 'ESTJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·完美溫和版',
      tagline: '你嘅執行力同標準一樣咁高',
      encourage: '你嘅 standard 係高咗啲，但要記住人唔係 machine',
      emoji: '📊',
    ),
    'ESTJ_2w1': PersonalityName(
      mbti: 'ESTJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·無私守則版',
      tagline: '你帶人嘅方式係嚴格但有愛心',
      encourage: '你嚴格得嚟有愛心，員工會 respect 你',
      emoji: '📊',
    ),
    'ESTJ_2w3': PersonalityName(
      mbti: 'ESTJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·熱心成就版',
      tagline: '你 manage 團隊時令人信服又有效率',
      encourage: '你 manage 又好又靚，係榜樣',
      emoji: '📊',
    ),
    'ESTJ_3w2': PersonalityName(
      mbti: 'ESTJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·耀眼協作版',
      tagline: '你嘅效率同人際技巧係完美組合',
      encourage: '你嘅 efficiency 同 people skills 係無敵',
      emoji: '📊',
    ),
    'ESTJ_3w4': PersonalityName(
      mbti: 'ESTJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·真實成就版',
      tagline: '你做事唔淨止快，仲要有 style',
      encourage: '你嘅執行力有 style，係你嘅 trademark',
      emoji: '📊',
    ),
    'ESTJ_4w3': PersonalityName(
      mbti: 'ESTJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·獨特展演版',
      tagline: '你嘅管理風格有個人特色，唔係死板嘅',
      encourage: '你嘅管理風格有個人 signature',
      emoji: '📊',
    ),
    'ESTJ_4w5': PersonalityName(
      mbti: 'ESTJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·深度原創版',
      tagline: '你對系統嘅理解有 depth，唔係得個殼',
      encourage: '你對 system 嘅理解有 depth',
      emoji: '📊',
    ),
    'ESTJ_5w4': PersonalityName(
      mbti: 'ESTJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·博學創作版',
      tagline: '你管理時會用到深厚嘅專業知識',
      encourage: '你嘅 knowledge 加 decision 係 powerful',
      emoji: '📊',
    ),
    'ESTJ_5w6': PersonalityName(
      mbti: 'ESTJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·系統思維版',
      tagline: '你每一項 decision 都有 data support',
      encourage: '你嘅 data-driven leadership 係好嘢',
      emoji: '📊',
    ),
    'ESTJ_6w5': PersonalityName(
      mbti: 'ESTJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·審慎智慧版',
      tagline: '你確保一切運作正常，係可靠嘅舵手',
      encourage: '你嘅 reliability 係團隊嘅 foundation',
      emoji: '📊',
    ),
    'ESTJ_6w7': PersonalityName(
      mbti: 'ESTJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·靈活應變版',
      tagline: '你有效率但唔 rigid，識得適應',
      encourage: '你嘅 efficiency 同 adaptability 係 perfect',
      emoji: '📊',
    ),
    'ESTJ_7w6': PersonalityName(
      mbti: 'ESTJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·歡樂策劃版',
      tagline: '你 drive 團隊向前，同時確保 risk 可控',
      encourage: '你嘅 drive 同 caution 係 winning combo',
      emoji: '📊',
    ),
    'ESTJ_7w8': PersonalityName(
      mbti: 'ESTJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·大膽前進版',
      tagline: '你 push 起嚟冇人跟到，但你 deliver',
      encourage: '你嘅 push 同 delivery 係 legendary',
      emoji: '📊',
    ),
    'ESTJ_8w7': PersonalityName(
      mbti: 'ESTJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·強大享樂版',
      tagline: '你天生係 leader，command respect',
      encourage: '你天生係 leader，inspire 身邊人',
      emoji: '📊',
    ),
    'ESTJ_8w9': PersonalityName(
      mbti: 'ESTJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·從容掌控版',
      tagline: '你有 authority 但唔會 micromanage',
      encourage: '你 authority 得嚟 calm，係最高境界',
      emoji: '📊',
    ),
    'ESTJ_9w8': PersonalityName(
      mbti: 'ESTJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·溫和堅韌版',
      tagline: '你 manage 團隊 calm 但有 force',
      encourage: '你 calm 嘅 authority 令人信服',
      emoji: '📊',
    ),
    'ESTJ_9w1': PersonalityName(
      mbti: 'ESTJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '📊 秩序建造者·和諧原則版',
      tagline: '你建立嘅 system 係 fair 同 efficient 嘅',
      encourage: '你建立嘅 system 係 fair 同 efficient',
      emoji: '📊',
    ),
    'ESTP_1w9': PersonalityName(
      mbti: 'ESTP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·完美溫和版',
      tagline: '你行動力驚人，而且每一次都精準',
      encourage: '你嘅行動力加精準度係 deadly combo',
      emoji: '🎯',
    ),
    'ESTP_1w2': PersonalityName(
      mbti: 'ESTP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·改革支援版',
      tagline: '你嘅行動係為咗創造價值俾人',
      encourage: '你嘅 action 係為咗 create value，keep going',
      emoji: '🎯',
    ),
    'ESTP_2w1': PersonalityName(
      mbti: 'ESTP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·無私守則版',
      tagline: '你幫人有 action，唔係講嘢咁簡單',
      encourage: '你幫人有 action，係最直接嘅善良',
      emoji: '🎯',
    ),
    'ESTP_2w3': PersonalityName(
      mbti: 'ESTP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·熱心成就版',
      tagline: '你出手幫人時總係恰到好處',
      encourage: '你出手幫人嘅 style 係你嘅 charm',
      emoji: '🎯',
    ),
    'ESTP_3w2': PersonalityName(
      mbti: 'ESTP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·耀眼協作版',
      tagline: '你嘅 charisma 同行動力令人信服',
      encourage: '你嘅 charisma 同 drive 係 magnetic',
      emoji: '🎯',
    ),
    'ESTP_3w4': PersonalityName(
      mbti: 'ESTP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·真實成就版',
      tagline: '你嘅行動有 style，唔係亂衝',
      encourage: '你嘅行動有 style，係你嘅 signature',
      emoji: '🎯',
    ),
    'ESTP_4w3': PersonalityName(
      mbti: 'ESTP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·獨特展演版',
      tagline: '你嘅膽識同品味係迷人嘅組合',
      encourage: '你嘅膽識同品味係迷人組合',
      emoji: '🎯',
    ),
    'ESTP_4w5': PersonalityName(
      mbti: 'ESTP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·深度原創版',
      tagline: '你嘅行動背後有 strategy',
      encourage: '你嘅 action 背後有 depth，令你更 powerful',
      emoji: '🎯',
    ),
    'ESTP_5w4': PersonalityName(
      mbti: 'ESTP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·博學創作版',
      tagline: '你行動前已經 mentally 模擬過好多次',
      encourage: '你嘅 mental rehearsal 係你嘅 secret weapon',
      emoji: '🎯',
    ),
    'ESTP_5w6': PersonalityName(
      mbti: 'ESTP', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·系統思維版',
      tagline: '你冒險時有 plan B 同 plan C',
      encourage: '你冒險有 plan，係精明嘅 risk taker',
      emoji: '🎯',
    ),
    'ESTP_6w5': PersonalityName(
      mbti: 'ESTP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·審慎智慧版',
      tagline: '你反應快又謹慎，係生存高手',
      encourage: '你嘅 quick reaction 同 caution 係生存智慧',
      emoji: '🎯',
    ),
    'ESTP_6w7': PersonalityName(
      mbti: 'ESTP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·靈活應變版',
      tagline: '你大膽但會諗過度過，係精明嘅冒險家',
      encourage: '你大膽又精明，係最成功嘅冒險家',
      emoji: '🎯',
    ),
    'ESTP_7w6': PersonalityName(
      mbti: 'ESTP', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·歡樂策劃版',
      tagline: '你永遠準備好下一個 adventure',
      encourage: '你永遠準備好下一個 adventure，live your best life',
      emoji: '🎯',
    ),
    'ESTP_8w7': PersonalityName(
      mbti: 'ESTP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·強大享樂版',
      tagline: '你嘅 presence 同 energy 主宰全場',
      encourage: '你嘅 energy 同 presence 係 unstoppable',
      emoji: '🎯',
    ),
    'ESTP_8w9': PersonalityName(
      mbti: 'ESTP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·從容掌控版',
      tagline: '你有 power 但識得收放自如',
      encourage: '你嘅 power 同 restraint 係成熟嘅象徵',
      emoji: '🎯',
    ),
    'ESTP_9w8': PersonalityName(
      mbti: 'ESTP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·溫和堅韌版',
      tagline: '你 chill 但一出手就知龍與鳳',
      encourage: '你 chill 但 powerful，呢個係最型嘅',
      emoji: '🎯',
    ),
    'ESTP_9w1': PersonalityName(
      mbti: 'ESTP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🎯 行動冒險家·和諧原則版',
      tagline: '你行動時有自己嘅 code，瀟灑但正直',
      encourage: '你行動有 code，係瀟灑嘅正直',
      emoji: '🎯',
    ),
    'INFJ_1w9': PersonalityName(
      mbti: 'INFJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·完美溫和版',
      tagline: '你對世界嘅理想藍圖好清晰，但要接受現實嘅 imperfect',
      encourage: '你嘅理想世界好美好，但現實都有佢嘅 beauty',
      emoji: '🔮',
    ),
    'INFJ_1w2': PersonalityName(
      mbti: 'INFJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·改革支援版',
      tagline: '你想改變世界，而且係以最有同理心嘅方式',
      encourage: '你改變世界嘅熱情好珍貴，但要由照顧自己開始',
      emoji: '🔮',
    ),
    'INFJ_2w1': PersonalityName(
      mbti: 'INFJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·無私守則版',
      tagline: '你幫人幫到有原則，唔係盲目付出',
      encourage: '你嘅付出係愛嘅表現，但都要接受自己嘅 need',
      emoji: '🔮',
    ),
    'INFJ_2w3': PersonalityName(
      mbti: 'INFJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·熱心成就版',
      tagline: '你默默支持每一個人，但都要記得照顧自己',
      encourage: '你照顧所有人係美德，但要 remember yourself',
      emoji: '🔮',
    ),
    'INFJ_3w2': PersonalityName(
      mbti: 'INFJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·耀眼協作版',
      tagline: '你想對世界有影響力，同時想被人欣賞',
      encourage: '你對世界嘅 impact 係真嘅，但你本來 already enough',
      emoji: '🔮',
    ),
    'INFJ_3w4': PersonalityName(
      mbti: 'INFJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·真實成就版',
      tagline: '你嘅使命感要有深度，唔係表面風光',
      encourage: '你嘅使命感好強，但都要 enjoy 當下',
      emoji: '🔮',
    ),
    'INFJ_4w3': PersonalityName(
      mbti: 'INFJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·獨特展演版',
      tagline: '你嘅靈魂好豐富，但有時好想被人明白',
      encourage: '你被明白嘅渴望好正常，你值得被 see',
      emoji: '🔮',
    ),
    'INFJ_5w4': PersonalityName(
      mbti: 'INFJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·博學創作版',
      tagline: '你對人性嘅理解有學術級嘅深度',
      encourage: '你嘅 insight 好珍貴，但要 share 出嚟',
      emoji: '🔮',
    ),
    'INFJ_5w6': PersonalityName(
      mbti: 'INFJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·系統思維版',
      tagline: '你洞察人心，但同時分析到背後嘅 system',
      encourage: '你嘅 vision 同 planning 係完美組合',
      emoji: '🔮',
    ),
    'INFJ_6w5': PersonalityName(
      mbti: 'INFJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·審慎智慧版',
      tagline: '你感受到周圍嘅 energy，同時保持警惕',
      encourage: '你嘅 intuition 好準，要信多啲自己',
      emoji: '🔮',
    ),
    'INFJ_6w7': PersonalityName(
      mbti: 'INFJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·靈活應變版',
      tagline: '你既 sensitive 又 curious，係好珍貴嘅組合',
      encourage: '你嘅敏感同樂觀可以 coexist',
      emoji: '🔮',
    ),
    'INFJ_7w6': PersonalityName(
      mbti: 'INFJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·歡樂策劃版',
      tagline: '你對未來充滿想像，但又有啲不安',
      encourage: '你嘅想像力係 gift，但都要有 solid plan',
      emoji: '🔮',
    ),
    'INFJ_7w8': PersonalityName(
      mbti: 'INFJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·大膽前進版',
      tagline: '你嘅 vision 大到想改變世界，而且你真係會試',
      encourage: '你嘅 vision 大到可以 changed the world',
      emoji: '🔮',
    ),
    'INFJ_8w7': PersonalityName(
      mbti: 'INFJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·強大享樂版',
      tagline: '你溫柔但強大，冇人估到你內心咁有力量',
      encourage: '你嘅溫柔力量係世上最強大嘅嘢',
      emoji: '🔮',
    ),
    'INFJ_8w9': PersonalityName(
      mbti: 'INFJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·從容掌控版',
      tagline: '你嘅直覺同力量結合，係和平嘅守護者',
      encourage: '你嘅 peacekeeping 能力係 trade，但要守好自己',
      emoji: '🔮',
    ),
    'INFJ_9w8': PersonalityName(
      mbti: 'INFJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·溫和堅韌版',
      tagline: '你 calm 但唔係 passive，內心有堅定嘅立場',
      encourage: '你嘅 calm 係力量，但要表達自己嘅 need',
      emoji: '🔮',
    ),
    'INFJ_9w1': PersonalityName(
      mbti: 'INFJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🔮 靈魂引渡者·和諧原則版',
      tagline: '你用同理心去建立和諧，係真正嘅和平使者',
      encourage: '你建立和諧嘅能力係天賦，但要 keep 自己嘅 voice',
      emoji: '🔮',
    ),
    'INFP_1w9': PersonalityName(
      mbti: 'INFP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·完美溫和版',
      tagline: '你嘅內心道德標準好高，但你溫柔到唔想傷人',
      encourage: '你嘅內心世界好純粹，但世界都值得你參與',
      emoji: '🌙',
    ),
    'INFP_1w2': PersonalityName(
      mbti: 'INFP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·改革支援版',
      tagline: '你想為世界帶嚟美好，而且係 action 嗰種',
      encourage: '你為世界帶嚟美好係你嘅使命',
      emoji: '🌙',
    ),
    'INFP_2w1': PersonalityName(
      mbti: 'INFP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·無私守則版',
      tagline: '你付出愛時有自己嘅原則，唔係討好型',
      encourage: '你嘅善良有原則，係最 healthy 嘅付出',
      emoji: '🌙',
    ),
    'INFP_2w3': PersonalityName(
      mbti: 'INFP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·熱心成就版',
      tagline: '你想被人欣賞你嘅善良，但善良本身 already 夠',
      encourage: '你值得被欣賞，唔好覺得自己唔重要',
      emoji: '🌙',
    ),
    'INFP_3w2': PersonalityName(
      mbti: 'INFP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·耀眼協作版',
      tagline: '你嘅創作想被人睇到，但更想被人理解',
      encourage: '你嘅才華值得被 seen，唔好收埋',
      emoji: '🌙',
    ),
    'INFP_3w4': PersonalityName(
      mbti: 'INFP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·真實成就版',
      tagline: '你嘅藝術要有 authenticity，唔係為流行',
      encourage: '你嘅創作係 authentic，呢個係最珍貴嘅',
      emoji: '🌙',
    ),
    'INFP_4w3': PersonalityName(
      mbti: 'INFP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·獨特展演版',
      tagline: '你想與眾不同，但又好想有人共鳴',
      encourage: '你嘅 uniqueness 係禮物，唔需要 justify',
      emoji: '🌙',
    ),
    'INFP_5w4': PersonalityName(
      mbti: 'INFP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·博學創作版',
      tagline: '你將情感化為詩歌同藝術，好有天份',
      encourage: '你嘅情感深度係藝術嘅源頭',
      emoji: '🌙',
    ),
    'INFP_5w6': PersonalityName(
      mbti: 'INFP', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·系統思維版',
      tagline: '你理解世界嘅方式係透過故事同符號',
      encourage: '你嘅故事同 symbols 可以 healing 好多人',
      emoji: '🌙',
    ),
    'INFP_6w5': PersonalityName(
      mbti: 'INFP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·審慎智慧版',
      tagline: '你對世界好敏感，但用創作去消化不安',
      encourage: '你嘅敏感係 superpower，唔係負擔',
      emoji: '🌙',
    ),
    'INFP_6w7': PersonalityName(
      mbti: 'INFP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·靈活應變版',
      tagline: '你喺夢想同現實之間搖擺，但都係你',
      encourage: '你喺夢想同現實之間可以找到 balance',
      emoji: '🌙',
    ),
    'INFP_7w6': PersonalityName(
      mbti: 'INFP', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·歡樂策劃版',
      tagline: '你嘅想像力無限，但有時需要落返地',
      encourage: '你嘅想像力無限，但都要有 action',
      emoji: '🌙',
    ),
    'INFP_7w8': PersonalityName(
      mbti: 'INFP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·大膽前進版',
      tagline: '你唔怕探索黑暗嘅主題，因為你信光',
      encourage: '你 explore 黑暗係為咗 find light',
      emoji: '🌙',
    ),
    'INFP_8w7': PersonalityName(
      mbti: 'INFP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·強大享樂版',
      tagline: '你溫柔嘅外表下有強大嘅信念',
      encourage: '你溫柔下有 backbone，呢個係最好嘅你',
      emoji: '🌙',
    ),
    'INFP_8w9': PersonalityName(
      mbti: 'INFP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·從容掌控版',
      tagline: '你為了保護心中嘅價值可以好堅定',
      encourage: '你 protect 自己嘅價值係啱嘅',
      emoji: '🌙',
    ),
    'INFP_9w8': PersonalityName(
      mbti: 'INFP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·溫和堅韌版',
      tagline: '你隨和但唔係冇主見，只係揀 battles',
      encourage: '你嘅 flexibility 係禮物，但都要 set boundaries',
      emoji: '🌙',
    ),
    'INFP_9w1': PersonalityName(
      mbti: 'INFP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🌙 夢境織造者·和諧原則版',
      tagline: '你追求 inner peace 同外在和諧嘅平衡',
      encourage: '你嘅 inner peace 係力量嘅來源',
      emoji: '🌙',
    ),
    'INTJ_1w9': PersonalityName(
      mbti: 'INTJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·完美溫和版',
      tagline: '你腦內嘅完美藍圖無人能及，但要記住世界唔係non-linear',
      encourage: '你嘅標準係高，但要記得人性唔係 code，唔可以完全 predict',
      emoji: '♟️',
    ),
    'INTJ_1w2': PersonalityName(
      mbti: 'INTJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·改革支援版',
      tagline: '你唔單止想做好件事，仲想幫成個系統升級，但要俾人喘氣',
      encourage: '你幫人係好事，但唔好將自己嘅標準強加俾人',
      emoji: '♟️',
    ),
    'INTJ_2w1': PersonalityName(
      mbti: 'INTJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·無私守則版',
      tagline: '你幫人都有自己一套標準，但有時都要放寬啲',
      encourage: '你嘅付出好有原則，但要記得接受別人不完美',
      emoji: '♟️',
    ),
    'INTJ_2w3': PersonalityName(
      mbti: 'INTJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·熱心成就版',
      tagline: '你暗中幫人仲要幫到最好睇，但自己嘅嘢呢？',
      encourage: '你幫人時有 expectation 好正常，但都要放過自己',
      emoji: '♟️',
    ),
    'INTJ_3w2': PersonalityName(
      mbti: 'INTJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·耀眼協作版',
      tagline: '你要贏同時要人鍾意你，野心同人脈你都要',
      encourage: '你嘅野心同魅力係資產，但都要停低感受下',
      emoji: '♟️',
    ),
    'INTJ_3w4': PersonalityName(
      mbti: 'INTJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·真實成就版',
      tagline: '你唔止要成功，仲要有型有深度，要求真係高',
      encourage: '你嘅成就同深度並存，但唔好活喺比較之中',
      emoji: '♟️',
    ),
    'INTJ_4w3': PersonalityName(
      mbti: 'INTJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·獨特展演版',
      tagline: '你既要與別不同又要得到掌聲，矛盾但迷人',
      encourage: '你與眾不同係優點，但唔需要證明俾全世界睇',
      emoji: '♟️',
    ),
    'INTJ_4w5': PersonalityName(
      mbti: 'INTJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·深度原創版',
      tagline: '你寧願孤獨都要保持深度，但有時出嚟行下啦',
      encourage: '你嘅深度係天賦，但要 connect with people 先完整',
      emoji: '♟️',
    ),
    'INTJ_5w4': PersonalityName(
      mbti: 'INTJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·博學創作版',
      tagline: '你鍾意研究奇特嘢仲要研究到出神入化',
      encourage: '你嘅知識好珍貴，但有時實踐比理論重要',
      emoji: '♟️',
    ),
    'INTJ_6w5': PersonalityName(
      mbti: 'INTJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·審慎智慧版',
      tagline: '你想信自己嘅分析，但又成日質疑，好攰㗎',
      encourage: '你嘅分析好透徹，但要信自己嘅判斷',
      emoji: '♟️',
    ),
    'INTJ_6w7': PersonalityName(
      mbti: 'INTJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·靈活應變版',
      tagline: '你一邊擔心未來一邊搵 fun，好矛盾但好有趣',
      encourage: '你嘅謹慎同好奇心可以並存，唔使二揀一',
      emoji: '♟️',
    ),
    'INTJ_7w6': PersonalityName(
      mbti: 'INTJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·歡樂策劃版',
      tagline: '你個腦同時 run 緊十個計劃，但每個都要 back up',
      encourage: '你嘅 vision 好宏大，但要 focus 先可以實現',
      emoji: '♟️',
    ),
    'INTJ_7w8': PersonalityName(
      mbti: 'INTJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·大膽前進版',
      tagline: '你唔只想試新嘢，仲要試到最盡最大',
      encourage: '你嘅野心係 fuel，但都要顧吓身邊人',
      emoji: '♟️',
    ),
    'INTJ_8w7': PersonalityName(
      mbti: 'INTJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·強大享樂版',
      tagline: '你要 control 一切，但都要留空間享受成果',
      encourage: '你嘅力量係天賦，但 vulnerability 都係一種力量',
      emoji: '♟️',
    ),
    'INTJ_8w9': PersonalityName(
      mbti: 'INTJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·從容掌控版',
      tagline: '你有 power 但唔需要 show off，低調嘅強者',
      encourage: '你強大得嚟平和，呢個係最好嘅狀態',
      emoji: '♟️',
    ),
    'INTJ_9w8': PersonalityName(
      mbti: 'INTJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·溫和堅韌版',
      tagline: '你表面平靜但內心有團火，係溫柔嘅力量',
      encourage: '你嘅平靜係力量，但都要適時表達立場',
      emoji: '♟️',
    ),
    'INTJ_9w1': PersonalityName(
      mbti: 'INTJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '♟️ 戰略軍師·和諧原則版',
      tagline: '你追求和諧但心中有把尺，平衡係你嘅藝術',
      encourage: '你追求和諧係美德，但都要 keep 住 authenticity',
      emoji: '♟️',
    ),
    'INTP_1w9': PersonalityName(
      mbti: 'INTP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·完美溫和版',
      tagline: '你追求理論嘅完美，但完美係process唔係destination',
      encourage: '你嘅理論可以完美，但現實世界有佢嘅 logic',
      emoji: '🔬',
    ),
    'INTP_1w2': PersonalityName(
      mbti: 'INTP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·改革支援版',
      tagline: '你覺得知識應該服務人類，理想主義者',
      encourage: '你嘅知識可以改變世界，但要 connect with people',
      emoji: '🔬',
    ),
    'INTP_2w1': PersonalityName(
      mbti: 'INTP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·無私守則版',
      tagline: '你分享知識時好有原則，唔係人人都肯教',
      encourage: '你 share 知識時可以 warm 啲，唔使永遠 detached',
      emoji: '🔬',
    ),
    'INTP_2w3': PersonalityName(
      mbti: 'INTP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·熱心成就版',
      tagline: '你鍾意 show off 你幾聰明，但你其實真係好聰明',
      encourage: '你嘅聰明值得被看見，唔好收收埋埋',
      emoji: '🔬',
    ),
    'INTP_3w2': PersonalityName(
      mbti: 'INTP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·耀眼協作版',
      tagline: '你想被認同係 genius，但又要保持謙遜，好攰㗎',
      encourage: '你嘅才華係真嘅，唔使扮低調',
      emoji: '🔬',
    ),
    'INTP_3w4': PersonalityName(
      mbti: 'INTP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·真實成就版',
      tagline: '你嘅理論要有 style，唔可以平凡',
      encourage: '你嘅 ideas 有 depth，值得俾更多人 know',
      emoji: '🔬',
    ),
    'INTP_4w3': PersonalityName(
      mbti: 'INTP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·獨特展演版',
      tagline: '你覺得自己嘅諗法係藝術品，同埋要俾人欣賞',
      encourage: '你嘅原創性係禮物，唔好收埋',
      emoji: '🔬',
    ),
    'INTP_4w5': PersonalityName(
      mbti: 'INTP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·深度原創版',
      tagline: '你沉迷於自己嘅思想迷宮，但有時要出返嚟',
      encourage: '你嘅思想迷宮好精彩，但都要定時出嚟呼吸',
      emoji: '🔬',
    ),
    'INTP_5w4': PersonalityName(
      mbti: 'INTP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·博學創作版',
      tagline: '你研究嘢係為咗美，而唔係為咗用，純粹嘅智慧',
      encourage: '你嘅求知慾係 gift，但唔好忘記生活',
      emoji: '🔬',
    ),
    'INTP_6w5': PersonalityName(
      mbti: 'INTP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·審慎智慧版',
      tagline: '你質疑一切，包括自己嘅質疑，無限 loop',
      encourage: '你嘅質疑精神好重要，但都要信自己一次',
      emoji: '🔬',
    ),
    'INTP_6w7': PersonalityName(
      mbti: 'INTP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·靈活應變版',
      tagline: '你對世界充滿好奇但又保持警惕，矛盾但迷人',
      encourage: '你嘅好奇心係寶藏，唔好俾恐懼限制',
      emoji: '🔬',
    ),
    'INTP_7w6': PersonalityName(
      mbti: 'INTP', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·歡樂策劃版',
      tagline: '你乜都想研究吓，但每個topic都要有深度',
      encourage: '你乜都想學係好事，但 depth over breadth 都重要',
      emoji: '🔬',
    ),
    'INTP_7w8': PersonalityName(
      mbti: 'INTP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·大膽前進版',
      tagline: '你唔怕挑釁主流觀點，仲要推到極致',
      encourage: '你嘅 intellect 係武器，但温柔都係一種力量',
      emoji: '🔬',
    ),
    'INTP_8w7': PersonalityName(
      mbti: 'INTP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·強大享樂版',
      tagline: '你嘅智力係武器，但你選擇用嚟拆解而唔係攻擊',
      encourage: '你嘅智力自信係好事，但要俾空間俾人',
      emoji: '🔬',
    ),
    'INTP_8w9': PersonalityName(
      mbti: 'INTP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·從容掌控版',
      tagline: '你對 nonsense 零容忍，但 choose your battles',
      encourage: '你選擇 battles 嘅智慧好成熟',
      emoji: '🔬',
    ),
    'INTP_9w8': PersonalityName(
      mbti: 'INTP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·溫和堅韌版',
      tagline: '你內心有好多 ideas，但唔急住話俾人聽',
      encourage: '你嘅 ideas 值得出聲，唔好永遠做觀察者',
      emoji: '🔬',
    ),
    'INTP_9w1': PersonalityName(
      mbti: 'INTP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🔬 概念建築師·和諧原則版',
      tagline: '你嘅腦袋永遠喺度分類同歸納，搵出真理',
      encourage: '你嘅分析力係天賦，但都要 trust your gut',
      emoji: '🔬',
    ),
    'ISFJ_1w9': PersonalityName(
      mbti: 'ISFJ', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·完美溫和版',
      tagline: '你照顧人照顧到無微不至，仲要有 quality',
      encourage: '你嘅溫柔照顧係 gift，但都要俾人照顧你',
      emoji: '🏡',
    ),
    'ISFJ_1w2': PersonalityName(
      mbti: 'ISFJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·改革支援版',
      tagline: '你默默付出，而且付出得好有 dignity',
      encourage: '你默默付出係愛嘅表現，你值得被看見',
      emoji: '🏡',
    ),
    'ISFJ_2w1': PersonalityName(
      mbti: 'ISFJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·無私守則版',
      tagline: '你嘅關懷有 boundary，係成熟嘅溫柔',
      encourage: '你嘅 care 有 boundary 係最 healthy 嘅',
      emoji: '🏡',
    ),
    'ISFJ_2w3': PersonalityName(
      mbti: 'ISFJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·熱心成就版',
      tagline: '你照顧人總係喺最恰到好處嘅時候',
      encourage: '你嘅細心令人感動，你係 irreplaceable 嘅',
      emoji: '🏡',
    ),
    'ISFJ_3w2': PersonalityName(
      mbti: 'ISFJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·耀眼協作版',
      tagline: '你嘅細心令人感動，但你唔覺得自己特別',
      encourage: '你嘅體貼係最有力量嘅嘢',
      emoji: '🏡',
    ),
    'ISFJ_3w4': PersonalityName(
      mbti: 'ISFJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·真實成就版',
      tagline: '你關心人嘅方式好有個人風格',
      encourage: '你關心人嘅方式好 unique，keep being you',
      emoji: '🏡',
    ),
    'ISFJ_4w3': PersonalityName(
      mbti: 'ISFJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·獨特展演版',
      tagline: '你嘅溫柔帶住一點與別不同',
      encourage: '你嘅溫柔帶著與別不同，呢個係你嘅 charm',
      emoji: '🏡',
    ),
    'ISFJ_4w5': PersonalityName(
      mbti: 'ISFJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·深度原創版',
      tagline: '你靜靜咁理解每一個人，係最溫柔嘅 observer',
      encourage: '你觀察人性嘅能力係 gift',
      emoji: '🏡',
    ),
    'ISFJ_5w4': PersonalityName(
      mbti: 'ISFJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·博學創作版',
      tagline: '你對人嘅觀察力好敏銳，但你唔會講出口',
      encourage: '你對人嘅 understanding 好深，share more',
      emoji: '🏡',
    ),
    'ISFJ_5w6': PersonalityName(
      mbti: 'ISFJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·系統思維版',
      tagline: '你 plan 好一切先行動，確保萬無一失',
      encourage: '你嘅 preparedness 令人安心',
      emoji: '🏡',
    ),
    'ISFJ_6w5': PersonalityName(
      mbti: 'ISFJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·審慎智慧版',
      tagline: '你永遠係第一個發現邊個唔開心嘅人',
      encourage: '你嘅 sensitivity 係 superpower',
      emoji: '🏡',
    ),
    'ISFJ_6w7': PersonalityName(
      mbti: 'ISFJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·靈活應變版',
      tagline: '你令身邊人感到被 care 同 safe',
      encourage: '你令身邊人 feel safe 係最珍貴嘅',
      emoji: '🏡',
    ),
    'ISFJ_7w6': PersonalityName(
      mbti: 'ISFJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·歡樂策劃版',
      tagline: '你溫柔又 playful，同你相處好舒服',
      encourage: '你嘅溫柔同 playful 嘅 balance 係完美',
      emoji: '🏡',
    ),
    'ISFJ_7w8': PersonalityName(
      mbti: 'ISFJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·大膽前進版',
      tagline: '你照顧人時都有自己嘅主張同底氣',
      encourage: '你嘅 care 有 backbone，呢個係成熟',
      emoji: '🏡',
    ),
    'ISFJ_8w7': PersonalityName(
      mbti: 'ISFJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·強大享樂版',
      tagline: '你溫柔但唔軟弱，關鍵時候好有力量',
      encourage: '你溫柔但 powerful 係最好嘅 combination',
      emoji: '🏡',
    ),
    'ISFJ_8w9': PersonalityName(
      mbti: 'ISFJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·從容掌控版',
      tagline: '你嘅保護欲係溫柔而堅定嘅',
      encourage: '你嘅 protective 係愛嘅表現',
      emoji: '🏡',
    ),
    'ISFJ_9w8': PersonalityName(
      mbti: 'ISFJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🏡 無聲守護者·溫和堅韌版',
      tagline: '你隨和但 always there when needed',
      encourage: '你隨和但 always there，呢個係你嘅 superpower',
      emoji: '🏡',
    ),
    'ISFP_1w9': PersonalityName(
      mbti: 'ISFP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·完美溫和版',
      tagline: '你嘅美學標準好高，但係溫柔嘅完美',
      encourage: '你嘅美學追求係 gift，但都要俾人睇到你嘅作品',
      emoji: '🎨',
    ),
    'ISFP_1w2': PersonalityName(
      mbti: 'ISFP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·改革支援版',
      tagline: '你嘅藝術係用來療癒人心嘅',
      encourage: '你嘅藝術有治癒力量，share it with the world',
      emoji: '🎨',
    ),
    'ISFP_2w1': PersonalityName(
      mbti: 'ISFP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·無私守則版',
      tagline: '你創作時心中有愛同原則',
      encourage: '你創作時心中有愛，呢個 shines through',
      emoji: '🎨',
    ),
    'ISFP_2w3': PersonalityName(
      mbti: 'ISFP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·熱心成就版',
      tagline: '你嘅作品令人 feel touched',
      encourage: '你嘅作品 touch 人心，唔好收埋',
      emoji: '🎨',
    ),
    'ISFP_3w2': PersonalityName(
      mbti: 'ISFP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·耀眼協作版',
      tagline: '你嘅藝術才華令人眼前一亮',
      encourage: '你嘅 talent 值得被 seen 同 celebrated',
      emoji: '🎨',
    ),
    'ISFP_3w4': PersonalityName(
      mbti: 'ISFP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·真實成就版',
      tagline: '你嘅創作有 authentic 嘅風格',
      encourage: '你嘅 authentic style 係最好嘅 signature',
      emoji: '🎨',
    ),
    'ISFP_4w3': PersonalityName(
      mbti: 'ISFP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·獨特展演版',
      tagline: '你嘅美感係天生嘅，仲要好有個人風格',
      encourage: '你嘅獨特美感係你最 powerful 嘅嘢',
      emoji: '🎨',
    ),
    'ISFP_4w5': PersonalityName(
      mbti: 'ISFP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·深度原創版',
      tagline: '你嘅作品反映咗你內心嘅深度',
      encourage: '你嘅 depth 係藝術嘅 soul',
      emoji: '🎨',
    ),
    'ISFP_5w4': PersonalityName(
      mbti: 'ISFP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·博學創作版',
      tagline: '你對美嘅 understanding 有好深嘅思考',
      encourage: '你嘅 creative depth 係 rare 嘅 gift',
      emoji: '🎨',
    ),
    'ISFP_5w6': PersonalityName(
      mbti: 'ISFP', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·系統思維版',
      tagline: '你創作前會做足 research，係認真嘅 artist',
      encourage: '你嘅 artistic research 令你嘅作品更 solid',
      emoji: '🎨',
    ),
    'ISFP_6w5': PersonalityName(
      mbti: 'ISFP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·審慎智慧版',
      tagline: '你透過藝術去理解同消化世界',
      encourage: '你透過 art 理解世界係你嘅 way',
      emoji: '🎨',
    ),
    'ISFP_6w7': PersonalityName(
      mbti: 'ISFP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·靈活應變版',
      tagline: '你嘅創作 playful 但又 meaningful',
      encourage: '你嘅 playful 創作係最自由嘅表達',
      emoji: '🎨',
    ),
    'ISFP_7w6': PersonalityName(
      mbti: 'ISFP', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·歡樂策劃版',
      tagline: '你嘅 imagination 冇極限，乜媒材都玩',
      encourage: '你嘅 imagination 冇 limit，keep playing',
      emoji: '🎨',
    ),
    'ISFP_7w8': PersonalityName(
      mbti: 'ISFP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·大膽前進版',
      tagline: '你嘅作品大膽又充滿生命力',
      encourage: '你嘅藝術大膽又自由，係 inspiring',
      emoji: '🎨',
    ),
    'ISFP_8w7': PersonalityName(
      mbti: 'ISFP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·強大享樂版',
      tagline: '你創作時好有 presence，作品有力量',
      encourage: '你創作時嘅 presence 係 powerful',
      emoji: '🎨',
    ),
    'ISFP_8w9': PersonalityName(
      mbti: 'ISFP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·從容掌控版',
      tagline: '你嘅藝術溫柔但有力',
      encourage: '你嘅 gentle power 喺藝術中 shine',
      emoji: '🎨',
    ),
    'ISFP_9w1': PersonalityName(
      mbti: 'ISFP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🎨 靜美藝術家·和諧原則版',
      tagline: '你嘅創作係和諧同美感嘅結合',
      encourage: '你嘅 art 係 harmony 同 beauty 嘅結合',
      emoji: '🎨',
    ),
    'ISTJ_1w2': PersonalityName(
      mbti: 'ISTJ', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·改革支援版',
      tagline: '你做好本份之餘仲會幫人跟進',
      encourage: '你嘅責任感令人敬佩，但要分啲俾人',
      emoji: '⚖️',
    ),
    'ISTJ_2w1': PersonalityName(
      mbti: 'ISTJ', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·無私守則版',
      tagline: '你幫人有 system，唔係亂咁幫',
      encourage: '你幫人有 system 係好事，但都要靈活',
      emoji: '⚖️',
    ),
    'ISTJ_2w3': PersonalityName(
      mbti: 'ISTJ', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·熱心成就版',
      tagline: '你幫人幫到令人覺得好可靠',
      encourage: '你嘅可靠性係 gift，唔好攰親自己',
      emoji: '⚖️',
    ),
    'ISTJ_3w2': PersonalityName(
      mbti: 'ISTJ', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·耀眼協作版',
      tagline: '你嘅 efficiency 同 reliability 無人能及',
      encourage: '你嘅 efficiency 同 care 係完美組合',
      emoji: '⚖️',
    ),
    'ISTJ_3w4': PersonalityName(
      mbti: 'ISTJ', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·真實成就版',
      tagline: '你做事有 quality，唔求快求靚',
      encourage: '你嘅 quality 標準係值得 respect',
      emoji: '⚖️',
    ),
    'ISTJ_4w3': PersonalityName(
      mbti: 'ISTJ', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·獨特展演版',
      tagline: '你嘅工作有風格，係低調嘅專業',
      encourage: '你嘅專業 style 係你嘅 signature',
      emoji: '⚖️',
    ),
    'ISTJ_4w5': PersonalityName(
      mbti: 'ISTJ', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·深度原創版',
      tagline: '你對細節嘅執著係一種藝術',
      encourage: '你對細節嘅關注係一種藝術',
      emoji: '⚖️',
    ),
    'ISTJ_5w4': PersonalityName(
      mbti: 'ISTJ', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·博學創作版',
      tagline: '你對專業領域嘅知識有深度嘅追求',
      encourage: '你嘅專業 depth 係好珍貴嘅',
      emoji: '⚖️',
    ),
    'ISTJ_5w6': PersonalityName(
      mbti: 'ISTJ', enneagram: '5w6', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·系統思維版',
      tagline: '你嘅 SOP 永遠係最新最完善嘅',
      encourage: '你嘅 SOP 係 masterpiece，但要留 space 給 創新',
      emoji: '⚖️',
    ),
    'ISTJ_6w5': PersonalityName(
      mbti: 'ISTJ', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·審慎智慧版',
      tagline: '你係 team 入面最 reliable 嗰個',
      encourage: '你嘅 reliability 係 team 嘅 backbone',
      emoji: '⚖️',
    ),
    'ISTJ_6w7': PersonalityName(
      mbti: 'ISTJ', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·靈活應變版',
      tagline: '你守規矩但唔死板，會靈活變通',
      encourage: '你守規矩但唔死板，呢個係最好嘅 balance',
      emoji: '⚖️',
    ),
    'ISTJ_7w6': PersonalityName(
      mbti: 'ISTJ', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·歡樂策劃版',
      tagline: '你鍾意穩定，但有時都會想試新嘢',
      encourage: '你嘅穩定性加上 flexibility 係 superpower',
      emoji: '⚖️',
    ),
    'ISTJ_7w8': PersonalityName(
      mbti: 'ISTJ', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·大膽前進版',
      tagline: '你做實事嘅效率驚人，又快又準',
      encourage: '你嘅 efficiency 同 decisiveness 令人佩服',
      emoji: '⚖️',
    ),
    'ISTJ_8w7': PersonalityName(
      mbti: 'ISTJ', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·強大享樂版',
      tagline: '你喺崗位上嘅 authority 係建立喺實力之上',
      encourage: '你嘅 competence 係你嘅 authority',
      emoji: '⚖️',
    ),
    'ISTJ_8w9': PersonalityName(
      mbti: 'ISTJ', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·從容掌控版',
      tagline: '你 low key 但 powerful，係穩重嘅存在',
      encourage: '你嘅 low key power 係成熟嘅表現',
      emoji: '⚖️',
    ),
    'ISTJ_9w8': PersonalityName(
      mbti: 'ISTJ', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·溫和堅韌版',
      tagline: '你平靜地處理一切，係團隊嘅定海神針',
      encourage: '你 calm 嘅 presence 係團隊嘅定心丸',
      emoji: '⚖️',
    ),
    'ISTJ_9w1': PersonalityName(
      mbti: 'ISTJ', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '⚖️ 堅實磐石·和諧原則版',
      tagline: '你嘅 consistency 令人安心，係可敬嘅存在',
      encourage: '你嘅 consistency 係你嘅 superpower',
      emoji: '⚖️',
    ),
    'ISTP_1w9': PersonalityName(
      mbti: 'ISTP', enneagram: '1w9', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·完美溫和版',
      tagline: '你動手做嘅嘢 zero defect，係工藝級',
      encourage: '你嘅手藝係 perfection，但都要 showcase 俾人睇',
      emoji: '🔧',
    ),
    'ISTP_1w2': PersonalityName(
      mbti: 'ISTP', enneagram: '1w2', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·改革支援版',
      tagline: '你嘅技能係用嚟幫人解決問題',
      encourage: '你嘅 skill 係為咗 help people，呢個係高尚',
      emoji: '🔧',
    ),
    'ISTP_2w1': PersonalityName(
      mbti: 'ISTP', enneagram: '2w1', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·無私守則版',
      tagline: '你幫人整嘢時好有原則，唔會 hea',
      encourage: '你幫人時可以 warm 啲，唔使永遠 stoic',
      emoji: '🔧',
    ),
    'ISTP_2w3': PersonalityName(
      mbti: 'ISTP', enneagram: '2w3', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·熱心成就版',
      tagline: '你默默出手幫人，瀟灑得嚟又好溫柔',
      encourage: '你嘅 silent help 係最溫柔嘅付出',
      emoji: '🔧',
    ),
    'ISTP_3w2': PersonalityName(
      mbti: 'ISTP', enneagram: '3w2', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·耀眼協作版',
      tagline: '你嘅 practical skills 令人驚嘆',
      encourage: '你嘅 practical genius 值得被 respect',
      emoji: '🔧',
    ),
    'ISTP_3w4': PersonalityName(
      mbti: 'ISTP', enneagram: '3w4', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·真實成就版',
      tagline: '你整嘅嘢又 functional 又有型',
      encourage: '你嘅 craft 有 art 嘅元素，keep creating',
      emoji: '🔧',
    ),
    'ISTP_4w3': PersonalityName(
      mbti: 'ISTP', enneagram: '4w3', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·獨特展演版',
      tagline: '你嘅 craftsmanship 有個人 signature',
      encourage: '你嘅手藝有 signature，係你嘅 style',
      emoji: '🔧',
    ),
    'ISTP_4w5': PersonalityName(
      mbti: 'ISTP', enneagram: '4w5', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·深度原創版',
      tagline: '你對 mechanics 嘅理解有藝術家嘅靈魂',
      encourage: '你對 mechanics 嘅理解有深度',
      emoji: '🔧',
    ),
    'ISTP_5w4': PersonalityName(
      mbti: 'ISTP', enneagram: '5w4', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·博學創作版',
      tagline: '你鑽研技術時有種禪意',
      encourage: '你嘅 craftsmanship 係一種 meditation',
      emoji: '🔧',
    ),
    'ISTP_6w5': PersonalityName(
      mbti: 'ISTP', enneagram: '6w5', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·審慎智慧版',
      tagline: '你 troubleshooting 時冷靜又精準',
      encourage: '你 troubleshooting 時係最 calm 嘅 genius',
      emoji: '🔧',
    ),
    'ISTP_6w7': PersonalityName(
      mbti: 'ISTP', enneagram: '6w7', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·靈活應變版',
      tagline: '你技術高超又靈活，乜都難唔到你',
      encourage: '你嘅 skill 同 flexibility 係 superpower',
      emoji: '🔧',
    ),
    'ISTP_7w6': PersonalityName(
      mbti: 'ISTP', enneagram: '7w6', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·歡樂策劃版',
      tagline: '你鍾意玩 tech gadgets 同 practical 嘢',
      encourage: '你玩 tech 嘅 passion 係 contagious',
      emoji: '🔧',
    ),
    'ISTP_7w8': PersonalityName(
      mbti: 'ISTP', enneagram: '7w8', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·大膽前進版',
      tagline: '你改裝起嘢嚟大膽又精準',
      encourage: '你改裝起來膽大心細，係 expert',
      emoji: '🔧',
    ),
    'ISTP_8w7': PersonalityName(
      mbti: 'ISTP', enneagram: '8w7', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·強大享樂版',
      tagline: '你操控工具嘅氣勢令人覺得你係專業',
      encourage: '你嘅 command 喺工具領域係無敵',
      emoji: '🔧',
    ),
    'ISTP_8w9': PersonalityName(
      mbti: 'ISTP', enneagram: '8w9', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·從容掌控版',
      tagline: '你 master 咗你嘅 craft，低調但強大',
      encourage: '你 master craft 嘅低調係最型嘅',
      emoji: '🔧',
    ),
    'ISTP_9w8': PersonalityName(
      mbti: 'ISTP', enneagram: '9w8', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·溫和堅韌版',
      tagline: '你平靜地做自己嘢，但出手就知有冇',
      encourage: '你 calm 嘅 competence 係最型嘅',
      emoji: '🔧',
    ),
    'ISTP_9w1': PersonalityName(
      mbti: 'ISTP', enneagram: '9w1', healthLevel: 'healthy',
      nameCanto: '🔧 寂靜工匠·和諧原則版',
      tagline: '你嘅 workflow 係順暢而精準嘅',
      encourage: '你嘅 workflow 係 perfect balance',
      emoji: '🔧',
    ),
  };

  static PersonalityName? getName(String mbti, String enneagram) {
    return _names['${mbti}_$enneagram'];
  }

  static bool hasName(String mbti, String enneagram) {
    return _names.containsKey('${mbti}_$enneagram');
  }

  static int get totalEntries => _names.length;

  static void addName(PersonalityName name) {
    _names['${name.mbti}_${name.enneagram}'] = name;
  }
}
